import "./globals.css";
import "./styless.css";
import "./stylesas.css";
import "./stylesaaaa.css";

import { Inter } from "next/font/google";
import Nav from "./_components/Nav";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <div className="diyw">
        <Nav></Nav>
        {children}
        <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
